name: test_project
description: A Flutter project using GetX, Hive, and Dio
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

# =========================================================
# Dependencies
# =========================================================
dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: any
  intl: ^0.20.2

  # State Management
  get: any

  # Local Database
  hive: any
  hive_flutter: any

  # Network
  dio: ^5.9.0
  connectivity_plus: any

  # Serialization / JSON
  json_annotation: any

# =========================================================
# Dev Dependencies
# =========================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any
  very_good_analysis: any

  # Code Generation
  build_runner: any
  hive_generator: any
  json_serializable: any

  # Testing
  test: ^1.25.15

# =========================================================
# Flutter Configuration
# =========================================================
flutter:
  uses-material-design: true

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-Italic.ttf
          style: italic
